name: Python
on: [pull, pull_request]

jobs:
  test:
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - run: python -munittest discover
